apiVersion: apps/v1
kind: Deployment
metadata:
  name: one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internetbanking
  template:
    metadata:
      labels:
        app: internetbanking
    spec:
      containers:
      - name: cont-1
        image: reyadocker/internetbankingrepo:latest
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "InternetBanking APP1"
---
apiVersion: v1
kind: Service
metadata:
  name: internetbanking
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: internetbanking
