apiVersion: apps/v1
kind: Deployment
metadata:
  name: two
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobilebanking
  template:
    metadata:
      labels:
        app: mobilebanking
    spec:
      containers:
      - name: cont-2
        image: reyadocker/mobilebankingrepo:latest
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "MobileBanking APP2"
---
apiVersion: v1
kind: Service
metadata:
  name: mobilebanking
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: mobilebanking
